Fix dependencies installation in workflows config

diff --git a/.github/workflows/compatibility.yml b/.github/workflows/compatibility.yml
--- a/.github/workflows/compatibility.yml
+++ b/.github/workflows/compatibility.yml
@@ -35,6 +35,12 @@ jobs:
         python -m pip install -e .
 
     - shell: bash -el {0}
+      name: Try installing optional packages
+      run: |
+        # Try installing one of the optional packages
+        pip install PySCIPOpt || pip install xpress || pip install gurobipy || pip install cplex || echo "All optional packages failed to install. Skipping."
+
+    - shell: bash -el {0}
       name: pip check
       run: |
         pip check || true  # Allow pip check to fail without failing the job
